nameSuffix: -big
bases:
- ../base

commonLabels:
  app: pmbench-big-manually-crirm-annotated
  size: big

configMapGenerator:
- name: pmbench
  literals:
    - extra='--setsize 50000 --mapsize 75000 200000 --initialize -a touch -j 8'

patchesStrategicMerge:
  - resources.yaml

commonAnnotations:
    cri-resource-manager.intel.com/memory-type: |
      pmbench: dram,pmem
    toptierlimit.cri-resource-manager.intel.com/pod: "10000000000"
    cri-resource-manager.intel.com/cold-start: |
      pmbench:
        duration: 60s
