apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus

resources:
  - prometheus.yaml
  - prometheus_rule.wca.yaml
  - prometheus_rule.16-compatibility-rules-new-to-old.yaml
  - service_account.yaml
  - service.yaml
  - operator/deployment.yaml
  - operator/service_account.yaml
  - operator/service.yaml
