global:
  scrape_interval: 1s
  evaluation_interval: 1s
rule_files:
  - 'prometheus.rules.yaml'
  - 'prometheus-apms.rules.yaml'
scrape_configs:
  - job_name: 'wca'
    static_configs:
    - targets:
      - '100.64.176.37:9100'
      - '100.64.176.38:9100'
      - '100.64.176.39:9100'
      - '100.64.176.40:9100'
  - job_name: 'fluentd'
    static_configs:
    - targets:
      - '100.64.176.37:24231'
      - '100.64.176.38:24231'
      - '100.64.176.39:24231'
      - '100.64.176.40:24231'
      - '100.64.176.200:24231'
      - '100.64.176.201:24231'
      - '100.64.176.202:24231'
      - '100.64.176.203:24231'
