nameSuffix: -small

bases:
- ../base

commonLabels:
  app: redis-small

configMapGenerator:
- name: memtier
  behavior: merge
  literals:
    - clients=30
    - threads=4
    - keymaximum=10000000 # 10M
    - datasize=32         # = 320M
