runner: !AllocationRunner
  measurement_runner: !MeasurementRunner
    node: !MesosNode
      mesos_agent_endpoint: 'http://127.0.0.1:5051'
      timeout: 5

    action_delay: 1.

    metrics_storage: !LogStorage
      output_filename: '/tmp/output_anomalies.log'

    # Decorate every metric with extra labels.
    extra_labels:
      env_id: "$HOST_IP"

  allocator: !NOPAllocator

  anomalies_storage: !KafkaStorage
    brokers_ips: ['$KAFKA_BROKER_IP:9092']
    topic: wca_anomalies
    max_timeout_in_seconds: 5.
