apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-mutilate
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 2
              memory: 100G
            limits:
              cpu: 2
              memory: 100G
        - name: mutilate
          resources:
            requests:
              cpu: 6
              memory: 1G
            limits:
              cpu: 6
              memory: 1G
