# Copyright (c) 2020 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wca-scheduler
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: wca-scheduler
  template:
    metadata:
      labels:
        app: wca-scheduler
    spec:
      hostNetwork: true
      terminationGracePeriodSeconds: 0
      nodeSelector:
        kubernetes.io/hostname: node36
      tolerations:
        - key: "master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: wca-scheduler
          image: 100.64.176.12:80/wca-scheduler:latest
          volumeMounts:
            - name: wca-scheduler-socket
              mountPath: /var/run/wca
            - name: wca-scheduler-config
              mountPath: /etc/wca-scheduler
          command:
            - pipenv
            - run
            - gunicorn
            - wca.scheduler.main:main('/etc/wca-scheduler/wca-scheduler-config.yaml')
            - -b
            - unix:/var/run/wca/wca-scheduler.sock
        - name: nginx
          image: nginx:latest
          ports:
            - name: wca-scheduler
              containerPort: 30180
              hostPort: 30180
          volumeMounts:
            - name: wca-scheduler-socket
              mountPath: /var/run/wca
            - name: wca-scheduler-server
              mountPath: /etc/nginx/conf.d

      volumes:
        - name: wca-scheduler-socket
          emptyDir: {}
        - name: wca-scheduler-server
          configMap:
            name: wca-scheduler-server 
        - name: wca-scheduler-config
          configMap:
            name: wca-scheduler-config 
