loggers:
#  "wca.extra.numa_allocator": "trace"
#  "wca.cgroups_allocations": "trace"
  "wca": "info"
runner: !AllocationRunner
  measurement_runner: !MeasurementRunner
    action_delay: 5
    node: !KubernetesNode
      cgroup_driver: cgroupfs
      ssl: !SSL
        server_verify: false
        client_cert_path: "/home/ppalucki/wca_remote_pycharm/apiserver-kubelet-client.crt"
        client_key_path: "/home/ppalucki/wca_remote_pycharm/apiserver-kubelet-client.key"
      kubelet_enabled: true
      kubelet_endpoint: "https://100.64.176.37:10250"
      monitored_namespaces: ["default"]

    # Disable all measurements based on perf system and resctrl
    enable_perf_uncore: true
    enable_derived_metrics: true
    gather_hw_mm_topology: false
    rdt_enabled: false
    event_names: []  # if uncommented disables metrics from perf event subsystem
    wss_reset_interval: 0
    #event_names:  # if uncommented disables metrics from perf event subsystem
    #- instructions
    #- cycles
    #- cache_misses
  # # - cache_references
    ## - stalls_mem_load
    #- mem_inst_retired_all_loads__rd081
    #- mem_inst_retired_all_stores__rd082
    
    # Metrics to files
    metrics_storage: !LogStorage
      output_filename: metrics.prom
      overwrite: true

    task_label_generators:
      aurora_instance: !TaskLabelRegexGenerator
        pattern: '.*-(\d+)-.{36}'
        repl: '\1'  # first match group
        source: 'task_id' #default

    extra_labels:
      node: !Env HOSTNAME

  allocator: !NUMAAllocator
    loop_min_task_balance: 0.0
    migrate_pages: true
    cgroups_memory_binding: false
    cgroups_memory_migrate: false
    double_match: false
    candidate: true
    dryrun: true

  allocations_storage: !LogStorage
    output_filename: allocations.prom
    overwrite: true
  anomalies_storage: !LogStorage
    output_filename: anomalies.prom
    overwrite: true
