apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-mutilate
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 2
              memory: 25G # valueSize*records = 20kB * 1M <= 25GB
            limits:
              cpu: 2
              memory: 25G
        - name: mutilate
          resources:
            requests:
              cpu: 4
              memory: 1G
            limits:
              cpu: 4
              memory: 1G
