apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: memcached-mutilate
spec:
  template:
    spec:
      containers:
        - name: memcached
          resources:
            requests:
              cpu: 2
              memory: 1G # valueSize*records = 0.8kB * 1M <= 1GB
