apiVersion: v1
kind: ServiceAccount
metadata:
  name: wca

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wca
rules:
- apiGroups: ['*']
  resources: ['*']
  verbs: ['*']

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wca
  namespace: wca
subjects:
  - kind: ServiceAccount
    name: wca
roleRef:
  kind: Role
  name: wca
  apiGroup: rbac.authorization.k8s.io

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wca
rules:
- apiGroups:
  - ''
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - list
  - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: wca
  namespace: wca
subjects:
- kind: ServiceAccount
  name: wca
  namespace: wca
roleRef:
  kind: ClusterRole
  name: wca
  apiGroup: rbac.authorization.k8s.io