resources:
- memcached.yaml
- mutilate.yaml

configMapGenerator:
- name: memcached
  literals:
  - memory=200000 # MB a.k.a. 200G
  - threads=4
  - cpus=0-1000
  - extra=

- name: mutilate
  literals:
    - threads=8
    - cpus=0-1000
    - value=10000              # 10k
    - load_records=1000000     # 1M = 10GB
    - records=100000           # 100k
    - qps=1000000              # 1M
    - conns=1
    - time=15          # seconds
    - extra=

patchesStrategicMerge:
  - resources.yaml
