apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sysbench-memory
spec:
  template:
    spec:
      containers:
        - name: sysbench
          resources:
            requests:
              cpu: 4
              memory: 16G
